Lookback Option Pricer: include/ExactLookbackPrice.h File Reference
ExactLookbackPrice.h File Reference
Exact closed-form pricing formulas for floating-strike lookback options.
Functions
double lookback_call_exact (double S0, double Smin, double r, double sigma, double T)
Exact price of a floating-strike lookback CALL option (Goldman, 1979).
double lookback_put_exact (double S0, double Smax, double r, double sigma, double T)
Exact price of a floating-strike lookback PUT option (Goldman, 1979).
Detailed Description
Exact closed-form pricing formulas for floating-strike lookback options.
Definition in file ExactLookbackPrice.h.
Function Documentation
lookback_call_exact()
double lookback_call_exact (const double S0, const double Smin, const double r, const double sigma, const double T)
Exact price of a floating-strike lookback CALL option (Goldman, 1979).
Parameters
S0 Current spot price.
Smin Minimum observed spot along the path.
r Risk-free rate.
sigma Volatility.
T Time to maturity.
Returns
Exact call price.
Exact price of a floating-strike lookback CALL option (Goldman, 1979).
Parameters
S0 Current spot price.
Smin Minimum observed spot.
r Risk-free rate.
sigma Volatility.
T Time to maturity.
Returns
Exact call price.
Definition at line 23 of file ExactLookbackPrice.cpp.
References norm_cdf().
Referenced by main().
lookback_put_exact()
double lookback_put_exact (const double S0, const double Smax, const double r, const double sigma, const double T)
Exact price of a floating-strike lookback PUT option (Goldman, 1979).
Parameters
S0 Current spot price.
Smax Maximum observed spot along the path.
r Risk-free rate.
sigma Volatility.
T Time to maturity.
Returns
Exact put price.
Exact price of a floating-strike lookback PUT option (Goldman, 1979).
Parameters
S0 Current spot price.
Smax Maximum observed spot.
r Risk-free rate.
sigma Volatility.
T Time to maturity.
Returns
Exact put price.
Definition at line 63 of file ExactLookbackPrice.cpp.
References norm_cdf().
Referenced by main().