Lookback Option Pricer: src/ExactLookbackPrice.cpp File Reference
ExactLookbackPrice.cpp File Reference
#include "ExactLookbackPrice.h"
#include <cmath>
Functions
double norm_cdf (double x)
Standard normal cumulative distribution function using erfc.
double lookback_call_exact (const double S0, const double Smin, const double r, const double sigma, const double T)
Exact price of a floating-strike lookback Call (Goldman, 1979).
double lookback_put_exact (const double S0, const double Smax, const double r, const double sigma, const double T)
Exact price of a floating-strike lookback Put (Goldman, 1979).
Function Documentation
lookback_call_exact()
double lookback_call_exact (const double S0, const double Smin, const double r, const double sigma, const double T)
Exact price of a floating-strike lookback Call (Goldman, 1979).
Exact price of a floating-strike lookback CALL option (Goldman, 1979).
Parameters
S0 Current spot price.
Smin Minimum observed spot.
r Risk-free rate.
sigma Volatility.
T Time to maturity.
Returns
Exact call price.
Definition at line 23 of file ExactLookbackPrice.cpp.
References norm_cdf().
Referenced by main().
lookback_put_exact()
double lookback_put_exact (const double S0, const double Smax, const double r, const double sigma, const double T)
Exact price of a floating-strike lookback Put (Goldman, 1979).
Exact price of a floating-strike lookback PUT option (Goldman, 1979).
Parameters
S0 Current spot price.
Smax Maximum observed spot.
r Risk-free rate.
sigma Volatility.
T Time to maturity.
Returns
Exact put price.
Definition at line 63 of file ExactLookbackPrice.cpp.
References norm_cdf().
Referenced by main().
norm_cdf()
double norm_cdf (double x)
Standard normal cumulative distribution function using erfc.
Parameters
x Input value.
Returns
CDF of standard normal at x.
Definition at line 9 of file ExactLookbackPrice.cpp.
Referenced by lookback_call_exact(), and lookback_put_exact().