Lookback Option Pricer: src/Greeks.cpp File Reference
Greeks.cpp File Reference
#include "Greeks.h"
#include <cmath>
#include <random>
#include <algorithm>
#include <vector>
Functions
double price_lookback_MC (const MCParams &p, unsigned long seed)
Forward declaration of Monte Carlo pricer used in Greeks computations.
static void price_delta_vega_pathwise (const MCParams &p, unsigned long seed, double &outPrice, double &outDelta, double &outVega)
Compute price, delta and vega pathwise in a single Monte Carlo run.
Greeks compute_greeks_MC (const MCParams &base, double bumpS, double bumpR, double bumpT, unsigned long seed)
Compute option price and Greeks using Monte Carlo.
Function Documentation
compute_greeks_MC()
Greeks compute_greeks_MC (const MCParams & base, double bumpS, double bumpR, double bumpT, unsigned long seed)
Compute option price and Greeks using Monte Carlo.
Delta and Vega are computed pathwise; Gamma, Rho and Theta use central finite differences with common random numbers for variance reduction.
Parameters
base Base Monte Carlo parameters.
bumpS Bump for underlying price (Gamma calculation).
bumpR Bump for interest rate (Rho calculation).
bumpT Bump for maturity (Theta calculation).
seed RNG seed for reproducibility.
Returns
Greeks structure with computed sensitivities.
Definition at line 120 of file Greeks.cpp.
References Greeks::delta, Greeks::gamma, Greeks::price, price_delta_vega_pathwise(), price_lookback_MC(), MCParams::r, Greeks::rho, MCParams::S0, MCParams::T, Greeks::theta, and Greeks::vega.
price_delta_vega_pathwise()
void price_delta_vega_pathwise (const MCParams & p, unsigned long seed, double & outPrice, double & outDelta, double & outVega) static
Compute price, delta and vega pathwise in a single Monte Carlo run.
This uses a pathwise derivative approach for Delta and Vega while accumulating the discounted payoff for price.
Parameters
p Monte Carlo parameters.
seed RNG seed for reproducibility.
outPrice Output parameter for price.
outDelta Output parameter for delta.
outVega Output parameter for vega.
Definition at line 31 of file Greeks.cpp.
References Call, MCParams::nPaths, MCParams::nSteps, MCParams::r, MCParams::S0, MCParams::sigma, MCParams::T, and MCParams::type.
Referenced by compute_greeks_MC().
price_lookback_MC()
double price_lookback_MC (const MCParams & params, const unsigned long seed)
Forward declaration of Monte Carlo pricer used in Greeks computations.
Forward declaration of Monte Carlo pricer used in Greeks computations.
Parameters
params Monte Carlo parameters (see MCParams).
seed RNG seed for reproducibility.
Returns
Discounted expected payoff (price).
Definition at line 34 of file LookbackOption.cpp.
Referenced by compute_greeks_MC().