Lookback Option Pricer: include/LookbackOption.h File Reference
LookbackOption.h File Reference
Data structures and functions for pricing floating-strike lookback options using Monte Carlo simulation.
#include <vector>
#include <string>
Classes
struct MCParams
Parameters for Monte Carlo pricing.
Enumerations
enum class LookbackType { Call , Put }
Type of lookback option.
Functions
double payoff_lookback (double ST, double minS, double maxS, LookbackType type)
Payoff of a floating-strike lookback option.
double price_lookback_MC (const MCParams &params, unsigned long seed=123)
Monte Carlo pricing of a floating-strike lookback option.
Detailed Description
Data structures and functions for pricing floating-strike lookback options using Monte Carlo simulation.
Definition in file LookbackOption.h.
Enumeration Type Documentation
LookbackType
enum class LookbackType strong
Type of lookback option.
Enumerator
Call
Put
Definition at line 16 of file LookbackOption.h.
Function Documentation
payoff_lookback()
double payoff_lookback (const double ST, const double Smin, const double Smax, const LookbackType type)
Payoff of a floating-strike lookback option.
Parameters
ST Terminal spot price.
minS Minimum spot along the path.
maxS Maximum spot along the path.
type Option type (Call/Put).
Returns
Payoff value for the path.
Parameters
ST Terminal asset price.
Smin Minimum asset price along the simulated path.
Smax Maximum asset price along the simulated path.
type Option type (Call or Put).
Returns
Payoff for the given path.
Definition at line 16 of file LookbackOption.cpp.
References Call.
Referenced by price_lookback_MC().
price_lookback_MC()
double price_lookback_MC (const MCParams & params, const unsigned long seed)
Monte Carlo pricing of a floating-strike lookback option.
Parameters
params Monte Carlo parameters (see MCParams).
seed RNG seed (default = 123).
Returns
Discounted Monte Carlo price.
Parameters
params Monte Carlo parameters (see MCParams).
seed RNG seed for reproducibility.
Returns
Discounted expected payoff (price).
Definition at line 34 of file LookbackOption.cpp.
References MonteCarlo::generate_path(), MCParams::nPaths, MCParams::nSteps, payoff_lookback(), MCParams::r, MCParams::S0, MCParams::sigma, MCParams::T, and MCParams::type.
Referenced by main().