Lookback Option Pricer: src/LookbackOption.cpp File Reference
LookbackOption.cpp File Reference
#include "LookbackOption.h"
#include "MonteCarlo.h"
#include <algorithm>
#include <cmath>
#include <vector>
Functions
double payoff_lookback (const double ST, const double Smin, const double Smax, const LookbackType type)
Payoff of a floating-strike lookback option.
double price_lookback_MC (const MCParams &params, const unsigned long seed)
Monte Carlo pricing of a floating-strike lookback option.
Function Documentation
payoff_lookback()
double payoff_lookback (const double ST, const double Smin, const double Smax, const LookbackType type)
Payoff of a floating-strike lookback option.
Parameters
ST Terminal asset price.
Smin Minimum asset price along the simulated path.
Smax Maximum asset price along the simulated path.
type Option type (Call or Put).
Returns
Payoff for the given path.
Definition at line 16 of file LookbackOption.cpp.
References Call.
Referenced by price_lookback_MC().
price_lookback_MC()
double price_lookback_MC (const MCParams & params, const unsigned long seed)
Monte Carlo pricing of a floating-strike lookback option.
Forward declaration of Monte Carlo pricer used in Greeks computations.
Parameters
params Monte Carlo parameters (see MCParams).
seed RNG seed for reproducibility.
Returns
Discounted expected payoff (price).
Definition at line 34 of file LookbackOption.cpp.
References MonteCarlo::generate_path(), MCParams::nPaths, MCParams::nSteps, payoff_lookback(), MCParams::r, MCParams::S0, MCParams::sigma, MCParams::T, and MCParams::type.
Referenced by compute_greeks_MC(), and main().